version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env  # Load environment variables from the .env file
    command: uvicorn app:app --host 0.0.0.0 --port 8000

  db:
    image: postgis/postgis:latest  # PostGIS image for PostgreSQL with GIS extension
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Use POSTGRES_PASSWORD from .env
      POSTGRES_USER: ${POSTGRES_USER}          # Use POSTGRES_USER from .env
      POSTGRES_DB: ${POSTGRES_DB}              # Use POSTGRES_DB from .env
      POSTGRES_HOST: db                        # Use db as the host for PostgreSQL container
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
